GameScene Class Reference
Contains all of the common fucctions and members needed to render a scene. A down stream Game scene will use the frame buffer and engine refrences stored here to render.
#include <GameScene.h>
Public Member Functions
GameScene (TinyEngineFrameBuffer &_framebuffer, TinyEngineRendererI &_renderer, TinyEngine &_engine)
Construct a new Game Scene object.
~GameScene ()
Destroy the Game Scene object.
void create () override
Create the scene after the object is created. This is for having multiple refrences to the same scene. Memory and configuration should only happen in this function.
void render () override
All framebuffer operations are done here and this is called only once per frame.
void update (double frameTime) override
Game updates and other time dependednt modifications should be done here, there is no gurentee this is run only.
void destroy () override
Destroy scene here. Only call if you do not need to use scene again. Ideally this would be stored in PSRAM instead.
Protected Attributes
TinyEngineFrameBuffer & m_framebuffer
Local refrance for framebuffer. User calls this instance to render.
TinyEngineRendererI & m_renderer
Local interface for renderer. This can be any renderer but only used for vsync.
TinyEngine & m_engine
Local Engine refrence. Used for assigning fps limit, profiling and binding GPIOs.
std::vector< Sprite * > sprites
Unused. But this is how a global ECS system would store sprites.
Detailed Description
Contains all of the common fucctions and members needed to render a scene. A down stream Game scene will use the frame buffer and engine refrences stored here to render.
Constructor & Destructor Documentation
GameScene()
GameScene::GameScene (TinyEngineFrameBuffer & _framebuffer, TinyEngineRendererI & _renderer, TinyEngine & _engine) [inline]
Construct a new Game Scene object.
Parameters
_framebuffer
_renderer
_engine
        : m_framebuffer(_framebuffer), m_renderer(_renderer), m_engine(_engine) {
    };
References m_engine, m_framebuffer, and m_renderer.
~GameScene()
GameScene::~GameScene ()
Destroy the Game Scene object.
                      {
}
Member Function Documentation
create()
void GameScene::create () [override], [virtual]
Create the scene after the object is created. This is for having multiple refrences to the same scene. Memory and configuration should only happen in this function.
Implements SceneI.
Reimplemented in SnakeGame.
                       {
}
Referenced by SnakeGame::create().
destroy()
void GameScene::destroy () [override], [virtual]
Destroy scene here. Only call if you do not need to use scene again. Ideally this would be stored in PSRAM instead.
Implements SceneI.
Reimplemented in SnakeGame.
                        {
};
Referenced by SnakeGame::destroy().
render()
void GameScene::render () [override], [virtual]
All framebuffer operations are done here and this is called only once per frame.
Implements SceneI.
Reimplemented in SnakeGame.
                       {
    // sprintf(string, "Total Heap: %d bytes | Free: %d \n", getTotalHeap(), getFreeHeap());
    // m_framebuffer.draw_string(string, 5, 40, 15);
    //
    // sprintf(string, "Total Render Time %dms / %dms\n", m_engine.get_profile_render_loop_time(),
    // m_engine.get_profile_main_loop_time());
    // m_framebuffer.draw_string(string, 5, 50, 15);
    //
    // sprintf(string, "Total Update: %dms / %dms\n",
    // m_engine.get_profile_update_loop_time(), m_engine.get_profile_main_loop_time());
    // m_framebuffer.draw_string(string, 5, 60, 15);
    // sprintf(string, "Total allocated: %d bytes\n", info.uordblks);
    // m_framebuffer.draw_string(string, 5, 60, 15);
    // sprintf(string, "Total free: %d bytes\n", info.fordblks);
    // m_framebuffer.draw_string(string, 5, 70, 15);
    // sprintf(string, "Total heap size: %d bytes\n", info.arena);
    // m_framebuffer.draw_string(string, 5, 80, 15);
    // sprintf(string, "Largest free block: %d bytes\n", info.ordblks);
    // m_framebuffer.draw_string(string, 5, 90, 15);
    sprintf(string, "FPS: %d\r\n", m_engine.get_fps());
    m_framebuffer.draw_string(string, 5, 10, 15);
    // sprintf(string, "Press W, A, S, D for movement.\r\n");
    // m_framebuffer.draw_string(string, 5, 20, 15);
    // sprintf(string, "Press X to quit the game.\r\n");
    // m_framebuffer.draw_string(string, 5, 30, 15);
};
References m_engine, and m_framebuffer.
Referenced by SnakeGame::render().
update()
void GameScene::update (double frameTime) [override], [virtual]
Game updates and other time dependednt modifications should be done here, there is no gurentee this is run only.
Parameters
frameTime
Implements SceneI.
Reimplemented in SnakeGame.
                                       {
    info = mallinfo();
};
Referenced by SnakeGame::update().
Member Data Documentation
m_engine
TinyEngine& GameScene::m_engine [protected]
Local Engine refrence. Used for assigning fps limit, profiling and binding GPIOs.
Referenced by SnakeGame::create(), GameScene(), and render().
m_framebuffer
TinyEngineFrameBuffer& GameScene::m_framebuffer [protected]
Local refrance for framebuffer. User calls this instance to render.
Referenced by GameScene(), render(), and SnakeGame::render().
m_renderer
TinyEngineRendererI& GameScene::m_renderer [protected]
Local interface for renderer. This can be any renderer but only used for vsync.
Referenced by GameScene(), and SnakeGame::render().
sprites
std::vector<Sprite*> GameScene::sprites [protected]
Unused. But this is how a global ECS system would store sprites.
The documentation for this class was generated from the following files:
C:/Users/GRHRehabTech/Desktop/Abinash Work Term/REGI/Firmware/REGI-TinyEngine/inc/GameScene.h
C:/Users/GRHRehabTech/Desktop/Abinash Work Term/REGI/Firmware/REGI-TinyEngine/src/GameScene.cpp