SnakeGame Class Reference
Public Member Functions
SnakeGame (TinyEngineFrameBuffer &_framebuffer, TinyEngineRendererI &_renderer, TinyEngine &_engine)
void create () override
Create the scene after the object is created. This is for having multiple refrences to the same scene. Memory and configuration should only happen in this function.
void render () override
All framebuffer operations are done here and this is called only once per frame.
void update (double frameTime) override
Game updates and other time dependednt modifications should be done here, there is no gurentee this is run only.
void destroy () override
Destroy scene here. Only call if you do not need to use scene again. Ideally this would be stored in PSRAM instead.
Public Member Functions inherited from GameScene
GameScene (TinyEngineFrameBuffer &_framebuffer, TinyEngineRendererI &_renderer, TinyEngine &_engine)
Construct a new Game Scene object.
~GameScene ()
Destroy the Game Scene object.
Additional Inherited Members
Protected Attributes inherited from GameScene
TinyEngineFrameBuffer & m_framebuffer
Local refrance for framebuffer. User calls this instance to render.
TinyEngineRendererI & m_renderer
Local interface for renderer. This can be any renderer but only used for vsync.
TinyEngine & m_engine
Local Engine refrence. Used for assigning fps limit, profiling and binding GPIOs.
std::vector< Sprite * > sprites
Unused. But this is how a global ECS system would store sprites.
Detailed Description
Constructor & Destructor Documentation
SnakeGame()
SnakeGame::SnakeGame (TinyEngineFrameBuffer & _framebuffer, TinyEngineRendererI & _renderer, TinyEngine & _engine) [inline]
        : GameScene(_framebuffer, _renderer, _engine)
    {
    }
Member Function Documentation
create()
void SnakeGame::create () [override], [virtual]
Create the scene after the object is created. This is for having multiple refrences to the same scene. Memory and configuration should only happen in this function.
Reimplemented from GameScene.
{
    GameScene::create();
    // Flag to signal the gameover
    gameover = 0;
    // Initial coordinates of the snake
    x_snake = WIDTH_SNAKE / 2;
    y_snake = HEIGHT_SNAKE / 2;
    // Initial coordinates of the fruit
    fruitx_snake = rand() % WIDTH_SNAKE;
    fruity_snake = rand() % HEIGHT_SNAKE;
    while (fruitx_snake == 0)
        fruitx_snake = rand() % WIDTH_SNAKE;
    while (fruity_snake == 0)
        fruity_snake = rand() % HEIGHT_SNAKE;
    // Score initialzed
    score_snake = 0;
    m_engine.bind_serial_input_event(
        'w',
        [&]
        {
            key_snake = 3;
        }
    );
    m_engine.bind_serial_input_event(
        'a',
        [&]
        {
            key_snake = 1;
        }
    );
    m_engine.bind_serial_input_event(
        's',
        [&]
        {
            key_snake = 4;
        }
    );
    m_engine.bind_serial_input_event(
        'd',
        [&]
        {
            key_snake = 2;
        }
    );
    m_engine.bind_serial_input_event(
        'x_snake',
        [&]
        {
            gameover = 1;
        }
    );
    m_engine.bind_serial_input_event(
        'f',
        [&]
        {
            x_snake = fruitx_snake;
            y_snake = fruity_snake;
        }
    );
}
References GameScene::create(), and GameScene::m_engine.
destroy()
void SnakeGame::destroy () [override], [virtual]
Destroy scene here. Only call if you do not need to use scene again. Ideally this would be stored in PSRAM instead.
Reimplemented from GameScene.
{
    GameScene::destroy();
}
References GameScene::destroy().
render()
void SnakeGame::render () [override], [virtual]
All framebuffer operations are done here and this is called only once per frame.
Reimplemented from GameScene.
{
    GameScene::render();
    m_framebuffer.clear(0); // colors are based on pallette
    // Creating top wall
    // for (int i = 0; i < WIDTH_SNAKE; i++) {
    // // printf("-");
    // m_framebuffer.draw_pix_snakeel(i, 0, 66);
    // }
    // printf("\n");
    m_framebuffer.draw_outline_rectangle(0, 0, 320 - 1, 240 - 1, 45);
    // m_framebuffer.draw_pix_snakeel(x_snake, y_snake, 66);
    m_framebuffer.draw_filled_rectangle(x_snake, y_snake, 10, 10, 45);
    // m_framebuffer.draw_pix_snakeel(fruitx_snake, fruity_snake, 66);
    m_framebuffer.draw_filled_rectangle(fruitx_snake, fruity_snake, 5, 5, 31);
    for (int k = 0; k < snakeTailLen; k++)
    {
        m_framebuffer.draw_filled_rectangle(snakeTailx_snake[k], snakeTaily_snake[k], 10, 10, 45);
    }
    if (x_snake > 320) x_snake = 0;
    if (x_snake < 0) x_snake = 320;
    if (y_snake > 240) y_snake = 0;
    if (y_snake < 0) y_snake = 0;
    // Creating bottom walls with '-'
    // for (int i = 0; i < WIDTH_SNAKE; i++) {
    // // printf("-");
    // m_framebuffer.draw_pix_snakeel(i, 239, 27);
    // }
    // printf("\n");
    // Print the score and instructions
    // printf("score = %d\r\n", score);
    // printf("Press W, A, S, D for movement.\r\n");
    // printf("Press x_snake to quit the game.\r\n");
    struct mallinfo info = mallinfo();
    // sprintf(fps_string, "Total Heap: %d by_snaketes | Free: %d \n", getTotalHeap(), getFreeHeap());
    // m_framebuffer.draw_string(fps_string, 5, 0, 100);
    //
    // sprintf(string, "Total Render Time %dms / %dms\n", m_engine.get_profile_render_loop_time(),
    // m_engine.get_profile_main_loop_time());
    // m_framebuffer.draw_string(string, 5, 0, 110);
    //
    // sprintf(string, "Total Update: %dms / %dms\n",
    // m_engine.get_profile_update_loop_time(), m_engine.get_profile_main_loop_time());
    // m_framebuffer.draw_string(string, 5, 0, 120);
    //
    // sprintf(string, "Total allocated: %d by_snaketes\n", info.uordblks);
    // m_framebuffer.draw_string(string, 5, 0, 60);
    // sprintf(string, "Total free: %d by_snaketes\n", info.fordblks);
    // m_framebuffer.draw_string(string, 5, 0, 70);
    // sprintf(string, "Total heap size: %d by_snaketes\n", info.arena);
    // m_framebuffer.draw_string(string, 5, 0, 80);
    // sprintf(string, "Largest free block: %d by_snaketes\n", info.ordblks);
    // m_framebuffer.draw_string(string, 5, 0, 90);
    // sprintf(string, "FPS: %d\r\n", m_engine.get_fps());
    // m_framebuffer.draw_string(string, 5, 0, 0);
    // sprintf(string, "score = %d\r\n", score);
    // m_framebuffer.draw_string(string, 5, 0, 10);
    // sprintf(string, "Press W, A, S, D for movement.\r\n");
    // m_framebuffer.draw_string(string, 5, 0, 20);
    // sprintf(string, "Press x_snake to quit the game.\r\n");
    // m_framebuffer.draw_string(string, 5, 0, 30);
    // sprintf(string, "Snake Coords: %d, %d\r\n", x_snake, y_snake);
    // m_framebuffer.draw_string(string, 5, 0, 40);
    // sprintf(string, "Food Coords: %d, %d\r\n", fruitx_snake, fruity_snake);
    // m_framebuffer.draw_string(string, 5, 0, 50);
    m_renderer.wait_for_vsync(); // If this is enabled debugging will not work, since this uses a blocking loop
    // with hardware event listeners it will just stay_snake here forever. Comment out the line when debugging
    m_framebuffer.swap_blocking();
}
References GameScene::m_framebuffer, GameScene::m_renderer, and GameScene::render().
update()
void SnakeGame::update (double frameTime) [override], [virtual]
Game updates and other time dependednt modifications should be done here, there is no gurentee this is run only.
Parameters
frameTime
Reimplemented from GameScene.
{
    GameScene::update(frameTime);
    // sprintf(string, "FPS: %d\r\n", m_engine.get_fps());
    // Updating the coordinates for continous
    // movement of snake
    int prevx_snake = snakeTailx_snake[0];
    int prevy_snake = snakeTaily_snake[0];
    int prev2x_snake, prev2y_snake;
    snakeTailx_snake[0] = x_snake;
    snakeTaily_snake[0] = y_snake;
    for (int i = 1; i < snakeTailLen; i++)
    {
        prev2x_snake = snakeTailx_snake[i];
        prev2y_snake = snakeTaily_snake[i];
        snakeTailx_snake[i] = prevx_snake;
        snakeTaily_snake[i] = prevy_snake;
        prevx_snake = prev2x_snake;
        prevy_snake = prev2y_snake;
    }
    // Changing the direction of movement of snake
    switch (key_snake)
    {
    case 1:
        x_snake--;
        break;
    case 2:
        x_snake++;
        break;
    case 3:
        y_snake--;
        break;
    case 4:
        y_snake++;
        break;
    default:
        break;
    }
    // If the game is over
    if (x_snake < 0 || x_snake >= WIDTH_SNAKE || y_snake < 0 || y_snake >= HEIGHT_SNAKE)
        gameover = 1;
    // Checks for collision with the tail (o)
    for (int i = 0; i < snakeTailLen; i++)
    {
        if (snakeTailx_snake[i] == x_snake && snakeTaily_snake[i] == y_snake)
            gameover = 1;
    }
    // If snake reaches the fruit
    // then update the score
    if (x_snake)
        if ((x_snake <= fruitx_snake && x_snake + 10 >= fruitx_snake) && (y_snake <= fruity_snake && y_snake + 10 >= fruity_snake))
        {
            fruitx_snake = rand() % WIDTH_SNAKE;
            fruity_snake = rand() % HEIGHT_SNAKE;
            while (fruitx_snake == 0)
                fruitx_snake = rand() % WIDTH_SNAKE;
            // Generation of new fruit
            while (fruity_snake == 0)
                fruity_snake = rand() % HEIGHT_SNAKE;
            score_snake += 10;
            snakeTailLen++;
        }
}
References GameScene::update().
The documentation for this class was generated from the following files:
C:/Users/GRHRehabTech/Desktop/Abinash Work Term/REGI/Firmware/REGI-TinyEngine/src/scenes/SnakeGame.h
C:/Users/GRHRehabTech/Desktop/Abinash Work Term/REGI/Firmware/REGI-TinyEngine/src/scenes/SnakeGame.cpp